#cloud-config

packages:
  - wordpress
package_update: true
package_upgrade: true
package_reboot_if_required: true

runcmd:
  - systemctl start httpd 
  - systemctl enable httpd
  - yum install -y https://wordpress.org/latest.tar.gz
  - tar -zxvf latest.tar.gz -C /var/www/html/
  - cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
  - chown -R apache:apache /var/www/html/wordpress/
  - chmod -R 755 /var/www/html/wordpress/
  - systemctl restart httpd

  write_files:
  - path: /var/www/html/wp-config.php
    content: |
      <?php
      define('DB_NAME', 'wordpress');
      define('DB_USER', 'wpuser');
      define('DB_PASSWORD', 'Riethuesli>12345');
      define('DB_HOST', '172.31.20.189');   

    owner: www-data:www-data
    permissions: '0644'
