# cloud-config
# wordpress reicht aus weil weitere packages die benötigt werden als dependencies sooderso heruntergeladen werden 
packages:
  - wordpress
package_update: true
package_upgrade: true
package_reboot_if_required: true
timezone: Europe/Zurich

runcmd:
  - systemctl enable httpd
  - systemctl start httpd 
  - yum install -y https://wordpress.org/latest.tar.gz
  - tar -zxvf latest.tar.gz -C /var/www/html/
  - cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
  - chown -R apache:apache /var/www/html/wordpress/
  - chmod -R 755 /var/www/html/wordpress/
  - systemctl restart httpd

  # WP Konfigurationsschritte nochmals

  - sed -i "s/database_name_here/wordpress/" /var/www/html/wordpress/wp-config.php
  - sed -i "s/username_here/wpuser/" /var/www/html/wordpress/wp-config.php
  - sed -i "s/password_here/X4#L6LwrN4V!w4&m^6pH98Li/" /var/www/html/wordpress/wp-config.php 
  - sed -i "s/localhost/172.31.20.189/" /var/www/html/wordpress/wp-config.php 
  