# cloud-config
packages:
  - mariadb-server

write_files:
  - path: /etc/mysql/mariadb.conf.d/50-server.cnf
    content: |
      [mysqld]
      bind-address = 172.31.20.189 
      log-error = /var/log/mysql/error.log

runcmd:
  - systemctl restart mariadb

  # Erstellen eines sicheren Root-Passworts
  - MYSQL_ROOT_PASSWORD=$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | head -c 54)
  - mysqladmin -u root password "$MYSQL_ROOT_PASSWORD"

  # MySQL-Befehle ausführen, um einen zusätzlichen Benutzer mit Zugriffsberechtigungen zu erstellen
  - mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "CREATE USER 'wpuser'@'%' IDENTIFIED BY 'X4#L6LwrN4V!w4&m^6pH98Li';"
  - mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "GRANT ALL PRIVILEGES ON *.* TO 'wpuser'@'%';"
  - mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "FLUSH PRIVILEGES;"

final_message: "Datenbank-Instanz wurde konfiguriert. Root-Passwort: $MYSQL_ROOT_PASSWORD"
